version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.12.3

    working_directory: /go/src/github.com/influxdata/line-protocol
    steps:
      - checkout

      - run: go get -v -t -d ./...
      - run: go get honnef.co/go/tools/...
      - run: go vet -v -unreachable=false ./...
      - run: go test -v ./...
      - run: staticcheck ./...
